<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'c8f7278c0e763c844d247f8dbd71f40d',
  'DATABASE_URL' => 'sqlite:///%kernel.project_dir%/var/database.sqlite',
);
